language: node_js
node_js:
  - "4"

before_install:
  - export NODE_ENV=test
  - npm install jshint -g

script:
  - npm run lint
  - FIELDDB_DATABASE_URL="https://public:none@corpusdev.lingsync.org" npm run test:coverage
